version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@1.0.2
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install: # Setup the required node version
        node-version: '14.19.1'
      - checkout
      - aws-cli/setup # Setup AWS CLI v2
      - eb/setup # Setup EB CLI
      - run:
          name: Front-End Install # Install all the dependencies for the angular application
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install # Install all the dependencies for the express application
          command: |
            npm run backend:install
      - run:
          name: Front-End Build # Compile a static site using the ng CLI
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build # Compile the express application using the typeScript CLI
          command: |
            npm run backend:build
      - run:
          name: Deploy Frontend # Deploy the compiled static site to S3 Static Hosting bucket
          command: |
            npm run frontend:deploy
      - run:
          name: Deploy Backend # Deploy the compiles express app to elastic beanstalk
          command: |
            npm run backend:deploy

workflows:
  build-workflow:
    jobs:
      - build
        filters:
            branches:
              only:
                - master
